apiVersion: v1
kind: Secret
namespace: mongodb
metadata:
  name: database-benchmark-mongo
type: Opaque
stringData:
    "connectionString.standard": "mongodb://developer:password@mongodb-benchmark-replica-set-0.mongodb-benchmark-replica-set-svc.mongodb.svc.cluster.local:27017/admin?ssl=false"
    "connectionString.standardSrv": "mongodb+srv://developer:password@kogito-mongodb-svc.kogito-benchmark.svc.cluster.local/admin?ssl=false"
    "password": "password"
    "username": "developer"